### PR TITLE
fix #70: Pg Backend: create_table_if_not_exists generates wrong sql

### LINKED ISSUE #70: Pg Backend: create_table_if_not_exists generates wrong sql
I have the following rust code: 

```RUST
use barrel::backend::Pg;
use barrel::types;
use barrel::*;

fn run_migrations() {
        let mut mig = Migration::new();
        mig.create_table_if_not_exists("cidades", |t| {
                t.add_column("id", types::primary());
                t.add_column("nome", types::text().nullable(false));
                t.add_column("cep_inicial", types::varchar(9));
                t.add_column("cep_final", types::varchar(9));
                t.add_column("uf", types::varchar(2));
                t.add_column("cod_ibge", types::integer());
        });

        println!("{}", mig.make::<Pg>());
}
```

Wich outputs:
```SQL
CREATE TABLE "cidades" IF NOT EXISTS ("id" SERIAL PRIMARY KEY NOT NULL, "nome" TEXT NOT NULL, "cep_inicial" VARCHAR(9) NOT NULL, "cep_final" VARCHAR(9) NOT NULL, "uf" VARCHAR(2) NOT NULL, "cod_ibge" INTEGER NOT NULL);
```

When running the generated SQL, the following error occurs:
```
ERROR: syntax error at or near "IF" LINHA 2: CREATE TABLE "entidades" IF NOT EXISTS ("id" SERIAL PRIMARY ...
```

Reading the [documentation](https://www.postgresql.org/docs/11/sql-createtable.html) the SQL should be:
```SQL
CREATE TABLE IF NOT EXISTS "cidades" ("id" SERIAL PRIMARY KEY NOT NULL, "nome" TEXT NOT NULL, "cep_inicial" VARCHAR(9) NOT NULL, "cep_final" VARCHAR(9) NOT NULL, "uf" VARCHAR(2) NOT NULL, "cod_ibge" INTEGER NOT NULL);
```

### PR DESCRIPTION
**Pull request by Pulgovisk**

### CODE REVIEW

**Comment by Pulgovisk** [comment]
@spacekookie Is this project alive?

**Comment by rippinrobr** [comment]
> @spacekookie Is this project alive?

Yes, it is

**Comment by spacekookie** [comment]
> @spacekookie Is this project alive?

Yes, but I'm kinda burnt out and taking a break from FOSS
development. Maybe @rippinrobr could take a look at it. Alternatively,
I'll be back at maintaining this mess in 2 weeks or so 😉

**Comment by rippinrobr** [comment]
> @spacekookie Is this project alive?
> Yes, but I'm kinda burnt out and taking a break from FOSS development. Maybe @rippinrobr could take a look at it. Alternatively, I'll be back at maintaining this mess in 2 weeks or so 😉

I am starting to get back from my time off, my home machine died so I'm in the process of rebuilding. Once that is up and running I will take a look at the PR.

**Comment by Pulgovisk** [comment]
Any news on this?

**Pull request merged**
